/**
 * Lista oficial de motivos Procon para classificação pela IA e seleção no
 * formulário de CRM. Compartilhada entre o backend (prompt do Gemini) e o
 * frontend (select do formulário). Strings EXATAS — não traduzir/reformular.
 */
export const MOTIVOS_PROCON: string[] = [
  'Customer - Problema com Pedido - Item Faltante',
  'Customer - Problema com Pedido - Itens Errados',
  'Customer - Problema com Pedido - Gosto Ruim',
  'Customer - Problemas com Pedido - Comida Derramada',
  'Customer - Problemas com Pedido - Cupom não aplicado',
  'Customer - Pedido não Entregue',
  'Customer - Pedido violado',
  'Customer - Problemas com pagamento',
  'Customer - Problema com Reembolso',
  'Customer - Impossibilidade de cancelamento - Pedido em preparação',
  'Customer - Problema com cancelamento - Endereço incorreto',
  'Customer - Problemas com Pedido - Comida Atraso na Entrega',
  'Customer - Desconhecimento de cobrança',
  'Customer - Observações não foram seguidas',
  'Customer - Problema com Indicação',
  'Customer - Objeto Estranho',
  'Customer - A comida não corresponde à descrição/imagem',
  'Customer - Comida Fria',
  'Customer - Comida vencida',
  'Customer - Pedido Cancelado',
  'Customer - Nota fiscal',
  'Customer - Escalação Solicitada - Segurança Alimentar',
  'Customer - Cliente não quis aceitar o pedido',
  'Customer - Entregador demora para pegar o pedido',
  'Customer - Porção insuficiente da refeição',
  'Customer - Problema com Pedido - Falha no Reembolso',
  'Customer - Keeta Pague Depois',
  'Customer - Documento Expirado',
  'Customer - Problemas com cadastro',
  'Rider - Problemas com a conta - Impossibilidade de acesso',
  'Rider - Problemas com penalidades e violações',
  'Rider - Problema com Campanha',
  'Rider - Duvidas sobre OL',
  'Rider - Cadastro em análise',
  'Rider - Cadastro Banido',
  'Rider - Histórico Criminal',
  'Rider - Sinistro',
  'Merchant - Problema com Cadastro',
  'Merchant - Problemas de Pagamento',
  'Merchant - Taxas',
  'Merchant - Problema com Pedido',
];
